### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by Omega359** [tangcent/easy-api#88]
Receiving this error when attempting to export an api in a directory (code -> export Postman)

IntelliJ 2019.2 Ultimate, JDK 11.

> [ERROR]	error to parse body
[TRACE]	java.util.ConcurrentModificationException
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1134)
	at com.itangcent.intellij.psi.DuckTypeHelper.resolve(DuckTypeHelper.kt:91)
	at com.itangcent.intellij.psi.DuckTypeHelper.resolve(DuckTypeHelper.kt:78)
	at com.itangcent.intellij.psi.AbstractPsiClassHelper.getTypeObject(AbstractPsiClassHelper.kt:175)
	at com.itangcent.idea.plugin.api.export.SpringClassExporter.parseResponseBody(SpringClassExporter.kt:604)
	at com.itangcent.idea.plugin.api.export.SpringClassExporter.processResponse(SpringClassExporter.kt:173)
	at com.itangcent.idea.plugin.api.export.SpringClassExporter.exportMethodApi(SpringClassExporter.kt:155)
	at com.itangcent.idea.plugin.api.export.SpringClassExporter.access$exportMethodApi(SpringClassExporter.kt:33)
	at com.itangcent.idea.plugin.api.export.SpringClassExporter$export$1.invoke(SpringClassExporter.kt:92)
	at com.itangcent.idea.plugin.api.export.SpringClassExporter$export$1.invoke(SpringClassExporter.kt:33)
	at com.itangcent.idea.plugin.api.export.SpringClassExporter.foreachMethod(SpringClassExporter.kt:671)
	at com.itangcent.idea.plugin.api.export.SpringClassExporter.export(SpringClassExporter.kt:91)
	at com.itangcent.idea.plugin.api.cache.CachedClassExporter$export$1$2.invoke(CachedClassExporter.kt:114)
	at com.itangcent.idea.plugin.api.cache.CachedClassExporter$export$1$2.invoke(CachedClassExporter.kt:23)
	at com.itangcent.intellij.context.ActionContext$runInReadUI$1.run(ActionContext.kt:293)
	at com.intellij.openapi.application.ReadAction.lambda$run$1(ReadAction.java:53)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:936)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:57)
	at com.intellij.openapi.application.ReadAction.run(ReadAction.java:53)
	at com.itangcent.intellij.context.ActionContext.runInReadUI(ActionContext.kt:290)
	at com.itangcent.idea.plugin.api.cache.CachedClassExporter$export$1.invoke(CachedClassExporter.kt:112)
	at com.itangcent.idea.plugin.api.cache.CachedClassExporter$export$1.invoke(CachedClassExporter.kt:23)
	at com.itangcent.intellij.context.ActionContext$runAsync$2.run(ActionContext.kt:169)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by tangcent** [comment]
Hi. I will fix this bug as soon as possible.
But it will take tow working days to release a new version.
